# ベースイメージ
FROM node:22.11.0-alpine AS base

RUN apk add --no-cache gcompat
WORKDIR /app

# package.json と tsconfig.json をコピー
COPY package*.json tsconfig.json ./

# 開発環境のすべての依存関係をインストール
RUN npm install

# ソースコードをコピー
COPY . .

# ポートを公開
EXPOSE 3000

# 開発環境用のホットリロードコマンド
CMD ["npx", "tsx", "watch", "src/index.ts"]
