version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/app:cached
      - /app/node_modules
      - /app/.git
    tty: true
    env_file:
      - .env
    networks:
      - ddd_sample_api_default
  db:
    image: postgres:16.3
    command: postgres -c jit=off
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - ddd_sample_api_default
networks:
  ddd_sample_api_default:
    external: true

volumes:
  db_data:
